on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/woofy@test
      with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
